subquery/subql-cosmos

packages/node/src/utils/cosmos.spec.ts, packages/node/src/utils/cosmos.ts
=> Add support for nested message filter

packages/node/src/utils/cosmos.ts
=> Support string as unit enum equality

.yarn/versions/30983b48.yml, packages/node/CHANGELOG.md, packages/node/src/configure/NodeConfig.ts, packages/node/src/configure/SubqueryProject.ts, packages/node/src/indexer/PoiBlock.ts, packages/node/src/indexer/benchmark.service.ts, packages/node/src/indexer/dynamic-ds.service.ts, packages/node/src/indexer/fetch.module.ts, packages/node/src/indexer/fetch.service.ts, packages/node/src/indexer/indexer.manager.ts, packages/node/src/indexer/indexer.module.ts, packages/node/src/indexer/mmr.service.ts, packages/node/src/indexer/poi.service.ts, packages/node/src/indexer/project.service.ts, packages/node/src/indexer/store.service.ts, packages/node/src/indexer/worker/block-dispatcher.service.ts, packages/node/src/indexer/worker/worker.builder.ts, packages/node/src/indexer/worker/worker.module.ts, packages/node/src/indexer/worker/worker.service.ts, packages/node/src/indexer/worker/worker.ts, packages/node/src/main.ts, packages/node/src/meta/meta.module.ts, packages/node/src/utils/autoQueue.ts, packages/node/src/utils/batch-size.ts, packages/node/src/utils/logger.ts, packages/node/src/yargs.ts, packages/types/src/interfaces.ts, yarn.lock
Get the latest changes from the main Subql Repo. This includes worker threads
=> Sync with main subql repo

packages/common-cosmos/src/project/models.ts, packages/node/src/indexer/indexer.manager.ts, packages/node/src/utils/cosmos.ts, packages/types/src/project.ts
FIlter out failed transaction by default and add Transaction Filters to include them
=> add tx filter

packages/node/package.json, yarn.lock
=> fix missing sequelize in latest node-core

.yarn/versions/3bd9beba.yml, packages/node/CHANGELOG.md, packages/node/package.json
=> [release] 20220930

.yarn/versions/3bd9beba.yml, packages/node/CHANGELOG.md, packages/node/package.json
Reverts subquery/subql-cosmos#60
=> Revert "[release] 20220930"

.yarn/versions/3bd9beba.yml, packages/node/CHANGELOG.md, packages/node/package.json
=> [release] 20220930 fix

packages/node/src/indexer/api.service.ts
=> fix rpc endpoint working with api key

packages/node/CHANGELOG.md, packages/node/package.json
=> [release] 20220930-2

.yarn/versions/440557a5.yml, .yarn/versions/e50f0933.yml, packages/node/CHANGELOG.md, packages/node/package.json
=> [release] 20221108

packages/node/package.json, packages/node/src/indexer/api.service.ts, packages/node/src/indexer/fetch.service.ts, packages/node/src/utils/cosmos.ts, yarn.lock
=> Handle rate limit

packages/node/src/indexer/blockDispatcher/worker-block-dispatcher.service.ts
Fixes https://github.com/subquery/subql-avalanche/issues/31
=> Fix missing blocks when using workers

packages/node/src/subcommands/reindex.module.ts
=> add apiService to reindex module

packages/node/src/utils/cosmos.spec.ts
Fix tests for `cosmos.spec.ts`
=> fix cosmos tests

packages/node/src/configure/SubqueryProject.ts, packages/node/src/indexer/api.service.test.ts, packages/node/src/indexer/api.service.ts, packages/node/src/utils/cosmos.ts, packages/types/src/interfaces.ts
=> add full block header to block

.yarn/versions/9ab712aa.yml, packages/node/CHANGELOG.md, packages/node/package.json, packages/types/CHANGELOG.md, packages/types/package.json, yarn.lock
=> [release] 20230123

packages/node/src/indexer/api.service.ts, packages/node/src/indexer/fetch.service.ts, packages/node/src/utils/cosmos.ts
Implement better error handling for RPC errors
=> error handling for rate limit and pruned node

packages/node/src/indexer/api.service.ts, packages/types/src/interfaces.ts
Fixes https://github.com/subquery/subql-cosmos/issues/111
=> Fix typo with validators

packages/node/package.json, packages/node/src/indexer/blockDispatcher/worker-block-dispatcher.service.ts, packages/node/src/indexer/worker/worker.unfinalizedBlocks.service.ts, yarn.lock
=> add unfinalized block service to workers

.yarn/versions/85e1ad95.yml, .yarn/versions/9cc93049.yml, .yarn/versions/b432b72f.yml, .yarn/versions/cf0d67ac.yml, .yarn/versions/dc14deed.yml, packages/common-cosmos/CHANGELOG.md, packages/common-cosmos/package.json, packages/node/CHANGELOG.md, packages/node/package.json, packages/types/CHANGELOG.md, packages/types/package.json, yarn.lock
=> [release] 20230517

.github/workflows/pr.yml, jest.config.js, package.json
Include coverage reports for tests in CI
=> CI coverage

packages/node/CHANGELOG.md, packages/node/package.json, packages/node/src/subcommands/mmrRegenerate.init.ts, yarn.lock
=> Release 20230608

.yarn/versions/39ef8103.yml, packages/common-cosmos/CHANGELOG.md, packages/common-cosmos/package.json, packages/node/CHANGELOG.md, packages/node/package.json
=> [release] 20230613

.github/PULL_REQUEST_TEMPLATE.md, packages/node/CHANGELOG.md, packages/node/package.json, packages/node/src/yargs.ts, yarn.lock
Update node core with various fixes and add `store-cache-upper-limit` flag to control the new cache limit
=> Update node-core and add store-cache-upper-limit flag

packages/node/CHANGELOG.md, packages/node/package.json, packages/node/src/indexer/cosmosClient.connection.ts, packages/node/src/indexer/fetch.module.ts, packages/node/src/indexer/indexer.module.ts, packages/node/src/indexer/project.service.ts, yarn.lock
=> sync with node-core 20230713

.yarn/versions/130719a6.yml, .yarn/versions/4e6833f8.yml, .yarn/versions/af6b290a.yml, .yarn/versions/b7679a51.yml, packages/common-cosmos/CHANGELOG.md, packages/common-cosmos/package.json, packages/node/CHANGELOG.md, packages/node/package.json, packages/types/CHANGELOG.md, packages/types/package.json
=> [release] 20230731

packages/common-cosmos/src/codegen/util.ts, packages/common-cosmos/src/project/versioned/ProjectManifestVersioned.ts
=> update validator types

.yarn/versions/e6ec3b52.yml, packages/common-cosmos/CHANGELOG.md, packages/common-cosmos/package.json, packages/node/CHANGELOG.md, packages/node/package.json
=> [release] 20230824

packages/common-cosmos/CHANGELOG.md, packages/common-cosmos/src/codegen/constants.ts
Updated telescope configs
- removing decoder/encoder functions that are unnecessary 
- Exclude query.proto from generated files
=> Update telescope config

.yarn/versions/1e85cad0.yml, packages/common-cosmos/CHANGELOG.md, packages/common-cosmos/package.json
Release for:
- `subql/common-cosmos`
=> [release] 20230904

.yarn/versions/2bac475a.yml, .yarn/versions/3ea03e53.yml, packages/common-cosmos/CHANGELOG.md, packages/common-cosmos/package.json, packages/node/CHANGELOG.md, packages/node/package.json
Test
Release for:
- node-cosmos 
- common-cosmos
=> [release] 20230920

packages/common-cosmos/CHANGELOG.md, packages/common-cosmos/package.json, packages/node/CHANGELOG.md, packages/node/package.json, packages/types/CHANGELOG.md, packages/types/package.json
major release for 
- node 3.0.0
- common 3.0.0
- types 3.0.0
=> [release] 20231004

packages/types/CHANGELOG.md, packages/types/src/project.ts
Fix typing for `RuntimeDatasourceTemplate`
=> fix RuntimeDatasourceTemplate generic typing

.yarn/versions/0a0d8c6f.yml, packages/common-cosmos/CHANGELOG.md, packages/common-cosmos/package.json, packages/node/CHANGELOG.md, packages/node/package.json, packages/node/src/yargs.ts, packages/types/CHANGELOG.md, packages/types/package.json
=> [release] 20231012 cosmos

packages/common-cosmos/CHANGELOG.md, packages/common-cosmos/src/codegen/codegen-controller.spec.ts, packages/common-cosmos/src/codegen/codegen-controller.ts, packages/common-cosmos/src/project/models.ts, packages/common-cosmos/src/project/types.ts, packages/common-cosmos/src/project/utils.ts, packages/common-cosmos/src/project/versioned/ProjectManifestVersioned.ts, packages/common-cosmos/src/project/versioned/v1_0_0/model.ts, packages/node/CHANGELOG.md, packages/node/src/configure/SubqueryProject.ts, packages/node/src/indexer/ds-processor.service.ts, packages/node/src/indexer/fetch.service.spec.ts, packages/node/src/indexer/fetch.service.ts, packages/node/src/indexer/indexer.manager.ts, packages/node/src/indexer/worker/worker.service.ts, packages/node/src/utils/cosmos.spec.ts, packages/node/src/utils/cosmos.ts, packages/node/src/utils/project.ts, packages/types/CHANGELOG.md, packages/types/src/project.ts
update types name to be consistent with main SDK
Fixes #184 
=> update types name to be consistent with main SDK

.yarn/versions/234ea531.yml, .yarn/versions/2b49ee2c.yml, .yarn/versions/3fc8a53f.yml, .yarn/versions/442db2ac.yml, .yarn/versions/514e0446.yml, .yarn/versions/609c9215.yml, .yarn/versions/729708d0.yml, .yarn/versions/79581ac3.yml, .yarn/versions/91c7e208.yml, .yarn/versions/9502455e.yml, .yarn/versions/aedfefc9.yml, .yarn/versions/c0efa143.yml, .yarn/versions/ed8a5e5e.yml, packages/common-cosmos/CHANGELOG.md, packages/common-cosmos/package.json, packages/node/CHANGELOG.md, packages/node/package.json, packages/types/CHANGELOG.md, packages/types/package.json
=> [release] 20231101

packages/types/src/global.ts
I think the `registry` was removed from one of the syncs
=> add missing global registry var

.github/workflows/node-cosmos-docker.yml, packages/node/Dockerfile, scripts/build.sh, tsconfig.json
=> [SKIP CI]fix docker ci

packages/node/CHANGELOG.md, packages/node/package.json, packages/node/src/yargs.ts, packages/types/CHANGELOG.md, packages/types/package.json, yarn.lock
Release for types:
- https://github.com/subquery/subql-cosmos/pull/199
=> [release] 20231106

.github/workflows/node-cosmos-docker.yml
=> add context to docker push actions

.github/workflows/node-cosmos-docker.yml, packages/node/.npmignore, packages/node/Dockerfile
=> update docker to install node globally

packages/common-cosmos/CHANGELOG.md, packages/common-cosmos/package.json, packages/node/CHANGELOG.md, packages/node/package.json
=> [release] 20231108

.github/workflows/node-cosmos-docker.yml
=> [SKIP CI] Fix release trigger pipeline

packages/node/CHANGELOG.md, packages/node/package.json, yarn.lock
=> [release] 20231225 cosmos

package.json, packages/node/package.json, yarn.lock
=> manual prerelease

packages/common-cosmos/package.json, packages/common-cosmos/src/codegen/constants.ts, yarn.lock
=> bump on telescope version

packages/common-cosmos/CHANGELOG.md, packages/common-cosmos/src/codegen/constants.ts
=> remove deprecated config, `fromPartial`

.yarn/versions/07e87407.yml, packages/node/src/indexer/dictionary.service.ts, packages/types/CHANGELOG.md
=> [release] 20240405

packages/common-cosmos/CHANGELOG.md, packages/common-cosmos/package.json, packages/node/CHANGELOG.md, packages/node/package.json, packages/types/CHANGELOG.md, packages/types/package.json
=> [release] 20240410

.github/workflows/benchmark.yml, .github/workflows/scripts/benchmark/Dockerfile, .github/workflows/scripts/benchmark/benchmarking.sh, .github/workflows/scripts/benchmark/cleanHistory.sh, .github/workflows/scripts/benchmark/queryMeta.sh
=> add missing script for benchmark

packages/node/src/indexer/api.service.ts, packages/node/src/utils/kyve/kyve.spec.ts, packages/node/src/utils/kyve/kyve.ts
Fixes and improvements on lcd client requests
=> Fixes and improvements

packages/node/Dockerfile
=> [SKIP CI] add python to Dockerfile

packages/node/CHANGELOG.md, packages/node/package.json
=> [release] 20240612

packages/node/CHANGELOG.md, packages/node/src/configure/SubqueryProject.ts, packages/node/src/utils/project.ts
A regression when updating the project loading. 
=> Fix chain types not being loaded

.yarn/versions/2ed81f15.yml, .yarn/versions/508f0d31.yml, packages/common-cosmos/CHANGELOG.md, packages/common-cosmos/package.json, packages/node/CHANGELOG.md, packages/node/package.json
=> [release] 20240823

packages/node/CHANGELOG.md, packages/node/package.json, yarn.lock
=> [release] 20240830

.yarn/versions/3fe26997.yml, packages/common-cosmos/CHANGELOG.md, packages/common-cosmos/package.json, packages/node/CHANGELOG.md, packages/node/package.json
=> [release] 20241022

.yarn/versions/0ea17037.yml, .yarn/versions/689ddd69.yml, .yarn/versions/9ea41ba3.yml, packages/common-cosmos/CHANGELOG.md, packages/common-cosmos/package.json, packages/node/CHANGELOG.md, packages/node/package.json, packages/types/CHANGELOG.md, packages/types/package.json, yarn.lock
=> [release] Bump `@subql/common` dependency

.yarn/versions/dc0c537d.yml, packages/common-cosmos/CHANGELOG.md, packages/common-cosmos/package.json, packages/node/CHANGELOG.md, packages/node/package.json
=> [release] 20241127

.yarn/versions/04782ba3.yml, .yarn/versions/3775e704.yml, packages/common-cosmos/CHANGELOG.md, packages/common-cosmos/package.json, packages/node/CHANGELOG.md, packages/node/package.json
=> [release] 20241217

packages/node/CHANGELOG.md, packages/node/package.json, packages/types/CHANGELOG.md, packages/types/package.json, yarn.lock
Switch to forked version of `@cosmjs/stargate` with changes from https://github.com/subquery/x-cosmjs/pull/1
=> Update to forked version of cosmjs stargate

packages/node/CHANGELOG.md, packages/node/src/utils/cosmos.spec.ts, packages/node/src/utils/cosmos.ts
Fixes being unable to stringify the block data because of circular references.
=> Fix json error stringifying new block structure

packages/node/CHANGELOG.md, packages/node/src/utils/cosmos.spec.ts, packages/node/src/utils/cosmos.ts
Process and include events if a transaction is failed. Before these would be skipped.
=> Fix logs not being included for failed transactions

packages/node/CHANGELOG.md, packages/node/src/indexer/api.service.ts, packages/node/src/indexer/dictionary/v1/dictionaryV1.spec.ts, packages/node/src/indexer/fetch.service.ts, packages/node/src/indexer/project.service.ts, packages/node/src/indexer/unfinalizedBlocks.service.ts, packages/node/src/indexer/worker/worker.service.ts, packages/node/src/utils/cosmos.ts
Fix timestamps not being included in headers and improve code reuse for parsing header time.
=> Include timestamps in headers

.github/workflows/pr.yml, packages/node/CHANGELOG.md, packages/node/src/configure/configure.module.ts, packages/node/src/subcommands/reindex.init.ts, packages/node/src/subcommands/reindex.module.spec.ts, packages/node/src/subcommands/reindex.module.ts, packages/node/src/subcommands/testing.module.spec.ts, packages/node/src/subcommands/testing.module.ts, packages/node/src/subcommands/testing.service.ts, packages/node/test/projectFixture/v1.0.0/project.yaml, packages/node/test/projectFixture/v1.0.0/schema.graphql
Fix missing dependency from testing command
=> Fix testing subcommand deps, add tests

packages/common-cosmos/CHANGELOG.md, packages/common-cosmos/package.json, packages/node/CHANGELOG.md, packages/node/package.json, yarn.lock
Update deps with a fix for indexes 
Fixes https://github.com/subquery/subql-cosmos/issues/342
=> Update subql deps, fixing index issue
