subquery/subql-cosmos

- packages/types/package.json
- packages/types/src/global.ts
- yarn.lock
Without these dependencies there is no type resolution for `api` and `registry`
> Add cosmos deps to types

- packages/node/src/indexer/api.service.ts
- packages/node/src/indexer/events.ts
- packages/node/src/indexer/project.service.ts
Change `chainId` to `chain` on meta http request.
Also improves message for unmatching chain Id
Fixes https://github.com/subquery/subql-cosmos/issues/47
> Fix chainId instead of chain

- packages/node/src/indexer/api.service.ts
Fixes unable to use endpoints from OnFinality with api key in url 
e.g. `https://juno.api.onfinality.io/rpc?apikey=<your-api-key>`
> Convert endpoint apikey query param to header

- packages/common-cosmos/src/project/models.ts
- packages/node/src/utils/cosmos.ts
- packages/types/src/project.ts
With current filters when user calls contract A, contract A calls contract B, an event happened in contract B,
in this case, B event is only catchable when filter contract A. This is a problem because contract A could be any contract.
This change allows improved filters on events so that it would be possible to filter by events on contract B
Transaction: https://www.mintscan.io/juno/txs/9B5073521AB7116AE2796073096FEF2F7009E6107F2BF47FBC36F216A0C0C68E
Filter:
```yaml
- handler: handleEvent
kind: cosmos/EventHandler
filter:
type: execute
attributes:
_contract_address: "juno1m7qmz49a9g6zeyzl032aj3rnsu856893cwryx8c4v2gf2s0ewv8qvtcsmx"
messageFilter:
type: "/cosmwasm.wasm.v1.MsgExecuteContract"
```
> Add the ability to filter by event attributes

- packages/node/src/indexer/api.service.ts
- packages/node/src/indexer/rpc-clients/HttpClient.ts
- packages/node/src/indexer/rpc-clients/RpcClient.ts
- packages/node/src/indexer/rpc-clients/WebsocketClient.ts
- packages/node/src/indexer/rpc-clients/index.ts
- packages/node/src/utils/cosmos.spec.ts
- packages/node/src/utils/cosmos.ts
Adds support for websocket connections with api keys. Also fixes not reusing http connections
Fixes https://github.com/subquery/subql-cosmos/issues/68
> Add websocket client that supports api keys

- packages/node/package.json
- packages/node/src/indexer/ds-processor.service.ts
- packages/node/src/indexer/indexer.manager.ts
- yarn.lock
- Fixes undefined reference to api in indexer.manager
- Fixes registry not being injected into DS processor sandbox
- Fixes vm2 version mismatch
> Fix datasource processor sandbox issues

- packages/node/src/indexer/api.service.ts
Support Enum lookups from proto files. Currently we only support Type lookups, if a type is dependant on an Enum that is in a different package/file then enum lookup is necessary to successfully register the type.
> support enum looks for proto files

- packages/node/src/indexer/api.service.ts
- packages/types/src/global.ts
- packages/types/src/interfaces.ts
Expose `validator()` from tendermint client to safe api in sandbox. This will allow projects to fetch validators of current block.
> expose validator() method from tmClient

- packages/node/src/indexer/api.service.ts
- packages/node/src/utils/cosmos.ts
`retryOnFailAxios` combined with retries from ConnectionPool class will multiply the number of retries. This can be fixed by removing `retryOnFailAxios`
> remove axios retries and cleanup logs

- packages/node/src/utils/cosmos.ts
Begin/End block events does not have messages or transactions associated with them. Trying to filter message data in those events will throw error.
> don't filter messages for begin/end block events

- packages/node/CHANGELOG.md
- packages/node/src/subcommands/testing.module.ts
Fix test subcommand not working because of incorrect dependencies
> Fix testing dependencies issue

- packages/node/CHANGELOG.md
- packages/node/src/utils/cosmos.ts
Catches an error and logs a warning when there is an event that doesn't have a messages that matches the message index
Example transaction:
https://sei.explorers.guru/transaction/8D4CA68E917E15652E10CB960DE604AEEB1B183D6E94A85E9CD98403F15550B7
> Catch error when event doesn't have a matching messsage

- .eslintignore
- .prettierignore
- packages/common-cosmos/CHANGELOG.md
- packages/common-cosmos/package.json
- packages/common-cosmos/src/codegen/codegen-controller.spec.ts
- packages/common-cosmos/src/codegen/codegen-controller.ts
- packages/common-cosmos/src/codegen/constants.ts
- packages/common-cosmos/src/codegen/index.ts
- packages/common-cosmos/src/codegen/templates/proto-interface.ts.ejs
- packages/common-cosmos/src/codegen/util.ts
- packages/common-cosmos/src/project/types.ts
- packages/common-cosmos/test/protoTest1/bad-cosmos-project.yaml
- packages/common-cosmos/test/protoTest1/project.yaml
- packages/common-cosmos/test/protoTest1/proto/osmosis/gamm/v1beta1/tx.proto
- packages/common-cosmos/test/protoTest1/proto/osmosis/poolmanager/v1beta1/swap_route.proto
- packages/node/CHANGELOG.md
- packages/node/src/configure/SubqueryProject.ts
- packages/node/src/indexer/api.service.ts
- packages/node/src/utils/project.ts
- yarn.lock
`codegen` support for cosmos (Protobufs to typescript typing)
https://github.com/subquery/subql/pull/1958
> Support for cosmos codegen

- packages/node/CHANGELOG.md
- packages/node/src/utils/cosmos.spec.ts
- packages/node/src/utils/cosmos.ts
User can only specify string or number values under filter in yaml manifests. If the decoded message values are of object types (such as Long), stringify them to compare it with filter values. 
> stringify object type decoded msg values for filtering

- package.json
- packages/common-cosmos/src/codegen/codegen-controller.spec.ts
- packages/node/src/utils/cosmos.spec.ts
CI gets stuck as jest does not exit after tests due to open handles. force exit jest after tests are completed
> force exit jest after test completion

- .github/workflows/node-cosmos-docker.yml
- packages/node/src/main.ts
Apply fix from other SDKs to check subcommands.
Also carry over changes to publish to subquery network docker org
> Fix main command check, add subquery network docker

- packages/common-cosmos/CHANGELOG.md
- packages/common-cosmos/src/codegen/codegen-controller.ts
- packages/common-cosmos/src/project/project.spec.ts
- packages/common-cosmos/src/project/types.ts
- packages/common-cosmos/src/project/versioned/v1_0_0/model.ts
- packages/common-cosmos/test/protoTest1/bad-chaintypes-project.yaml
- packages/common-cosmos/test/protoTest1/project.yaml
- packages/node/CHANGELOG.md
- packages/node/src/indexer/api.service.ts
- packages/node/src/utils/project.ts
- packages/types/CHANGELOG.md
- packages/types/src/project.ts
Instead of https://github.com/subquery/subql/pull/2069/files
`chainTypes` is considered as typo instead of `chaintypes`
> updated all chainTypes to chaintypes

- .yarn/versions/04541044.yml
- .yarn/versions/2f78370c.yml
- .yarn/versions/f4abbe6a.yml
- packages/common-cosmos/CHANGELOG.md
- packages/common-cosmos/package.json
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
Release for
- Fix on `types` on type
- bump `types` on node
- bump `types` on common
> [release] 20231005

- packages/node/CHANGELOG.md
- packages/node/src/utils/cosmos.spec.ts
- packages/node/src/utils/cosmos.ts
check if it is safe to use `in` operator on decoded contract call msg data before trying to match it with contractCall filter using `in` operator
Fixes #185 
> check if contractCall msg is Object before using `in` operator

- packages/node/CHANGELOG.md
- packages/node/src/indexer/indexer.manager.ts
- packages/node/src/subcommands/testing.module.ts
- packages/types/CHANGELOG.md
- packages/types/src/interfaces.ts
Fix events being potentially indexed multiple times because of message indexes being within a transaction not a block
Fix testing not working because of missing dependencies
> Fix indexing events multiple times

- .github/workflows/node-cosmos-docker.yml
- packages/node/Dockerfile
Update docker CI to build from source
> update docker to build from source - cosmos

- packages/common-cosmos/CHANGELOG.md
- packages/common-cosmos/src/codegen/codegen-controller.spec.ts
- packages/common-cosmos/src/codegen/codegen-controller.ts
- packages/common-cosmos/src/codegen/util.ts
Using path.basename is a more consistent on different OS
Fixes #https://github.com/subquery/subql/issues/2115
> update codegen pathing for protogen 

- packages/node/CHANGELOG.md
- packages/node/src/indexer/worker/worker.service.ts
Fix for 
```
2023-11-07T23:07:43.548Z <Worker Service #1-#1> ERROR Failed to fetch block 5300201 TypeError: Cannot read properties of null (reading 'hash')
```
According to Tendermint rpc types `Block ID of the previous block. This can be null when the currect block is height 1.` 
> Fix `TypeError: Cannot read properties of null (reading 'hash')`

- packages/node/CHANGELOG.md
- packages/node/src/indexer/rpc-clients/WebsocketClient.ts
I'm unsure why this code was here in the first place.
> Fix websocket client adding `/websocket` to the end of urls

- packages/common-cosmos/CHANGELOG.md
- packages/common-cosmos/package.json
- packages/common-cosmos/src/codegen/codegen-controller.ts
- packages/common-cosmos/src/codegen/constants.ts
- yarn.lock
> Update telescope with windows pathing fix

- .yarn/versions/087ac188.yml
- .yarn/versions/71e04cbc.yml
- .yarn/versions/764e4ca5.yml
- .yarn/versions/c8702b01.yml
- packages/common-cosmos/CHANGELOG.md
- packages/common-cosmos/package.json
> [release] 20240202

- packages/node/CHANGELOG.md
- packages/node/package.json
> Remove unused apollo-client dependency

- packages/node/CHANGELOG.md
- packages/node/src/utils/cosmos.spec.ts
- packages/node/src/utils/cosmos.ts
Background: cosmosjs deprecated long for message.callId in 0.32.0 https://github.com/cosmos/cosmjs/blob/main/CHANGELOG.md#changed-2. We made change to remove it in previous pr https://github.com/subquery/subql-cosmos/commit/ac68f61a7c4afb54a166ea3b759ac73e6de8b315#diff-7ed3b4e1e7a4809a4c839b761afb2eb1a0c45c6b5dd0f01c9cdb520cb80a015bL78.
From v3.11.0, We now facing any issue message filter not able to filter callId and handlers are not triggered. 
In this fix, we temp bring back `long` for message.callId, due to we have multiple version of `@cosmjs/stargate` installed in our sdk, and older version were installed from dependency `@kyvejs/xxx`. Use resolution in package.json also could not fixed version for `@cosmjs/stargate`.
We shall remove `long` again once `@kyvejs/xxx` …
> fix missing filter codeId in long type

- packages/node/CHANGELOG.md
- packages/node/src/indexer/dynamic-ds.service.spec.ts
- packages/node/src/indexer/dynamic-ds.service.ts
Creating dynamic data sources would not set any of the filter options. This now allows setting values and attributes to filter by.
> Implement assigning args to runtime dynamic ds

- packages/common-cosmos/CHANGELOG.md
- packages/common-cosmos/package.json
- packages/common-cosmos/src/codegen/codegen-controller.ts
- packages/common-cosmos/src/index.ts
- packages/common-cosmos/src/project/index.ts
- packages/types/CHANGELOG.md
- packages/types/package.json
- packages/types/src/index.ts
- packages/types/src/modular.ts
- yarn.lock
Part of task https://github.com/subquery/subql/pull/2456,  export interface to support generic cli method
> export cosmos module

- packages/common-cosmos/src/project/project.spec.ts
- packages/node/CHANGELOG.md
- packages/node/src/indexer/dynamic-ds.service.spec.ts
- packages/node/src/indexer/dynamic-ds.service.ts
Fixes dynamic ds creation so that it deals with undefined filter properties
> Fix dynamic ds creating emtpy values

- package.json
- packages/node/src/indexer/api.service.test.ts
- packages/node/src/indexer/api.service.ts
- packages/node/src/indexer/cosmosClient.connection.ts
- packages/node/src/indexer/types.ts
- packages/node/src/utils/cosmos.spec.ts
- packages/node/src/utils/cosmos.ts
- packages/node/src/utils/kyve/kyve.spec.ts
- packages/node/src/utils/kyve/kyve.ts
- packages/types/src/interfaces.ts
- yarn.lock
Improve the types to not be specific to a tendermint version. 
Update parsing logs/events to work with 0.50 changes
> Correcting types and event parsing for Cosmos SDK 0.50

- packages/node/CHANGELOG.md
- packages/node/src/utils/cosmos.spec.ts
- packages/node/src/utils/cosmos.ts
> Remove transactions that cant be decoded

- packages/node/CHANGELOG.md
- packages/node/src/utils/cosmos.spec.ts
- packages/node/src/utils/cosmos.ts
> Fix dictionary bigint

- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/node/src/indexer/api.service.ts
- packages/node/src/indexer/indexer.manager.ts
- packages/node/src/indexer/types.ts
- packages/node/src/utils/cosmos.spec.ts
- packages/node/src/utils/cosmos.ts
- yarn.lock
Uses a custom tendermint-rpc with https://github.com/cosmos/cosmjs/pull/1612 to allow support for finalizeBlockEvents
> Use forked version of tendermint-rpc for finalize block events

- packages/node/CHANGELOG.md
- packages/node/src/indexer/indexer.manager.ts
- packages/node/src/utils/cosmos.spec.ts
- packages/node/src/utils/cosmos.ts
- packages/types/CHANGELOG.md
- packages/types/src/interfaces.ts
This addresses some issues bought up by Pocketdex in https://github.com/subquery/subql-cosmos/pull/304
* Improve iterating messages and events, this matches changes made in the other SDKs and has a large performance increase
* Fixes non-message events (tx level events) not being able to be indexed
* Adds an event type field to events to determine what phase they have come from
* Adds decoded transactions, messages and events to the block.
> Improve block iteration, fix missing non-message events, add event type

- packages/node/CHANGELOG.md
- packages/node/src/indexer/cosmosClient.connection.ts
Comet BFT v1 was released and has a version string that was not correctly handled resulting in the wrong client being used. This follows the same logic as unreleased cosmjs changes
> Fix client selection for chains using comet 1.0
